version: 2.1

orbs:
  python: circleci/python@2.0.1

commands:
  python-deps:
    steps:
      - python/install-packages:
          pkg-manager: poetry

parameters:
  build-link-a:
    type: string
    description: build link URL for build A (job)
    default: ""
  build-link-b:
    type: string
    description: build link URL for build B (job)
    default: ""

jobs:
  validate:
    resource_class: small
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python-deps
      - run:
          name: Confirm builds are from the same project
          command: |
            poetry run python cli.py --validate \
              << pipeline.parameters.build-link-a >> \
              << pipeline.parameters.build-link-b >>
  info:
    parameters:
      n:
        type: integer
        default: 2
    parallelism: << parameters.n >>
    resource_class: medium
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python-deps
      - run:
          name: Parse build information
          command: |
            poetry run python cli.py --index=$CIRCLE_NODE_INDEX --info \
              << pipeline.parameters.build-link-a >> \
              << pipeline.parameters.build-link-b >>
      - persist_to_workspace:
          root: .
          paths:
            - job_info_*.yml
  visualize:
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Diff
          command: |
            # use --no-pager to disable interactive
            git --no-pager diff --no-index job_info_0.yml job_info_1.yml

workflows:
  diff-builds:
    when:
      and: # All must be true to trigger
        - << pipeline.parameters.build-link-a >>
        - << pipeline.parameters.build-link-b >>
    jobs:
      - validate
      - info:
          requires:
            - validate
      - visualize:
          requires:
            - info
