version: 2.1

parameters:
  build-link-a:
    type: string
    description: build link URL for build A (job)
    default: ""
  build-link-b:
    type: string
    description: build link URL for build B (job)
    default: ""

jobs:
  validate:
    resource_class: small
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Confirm builds are from the same project
          command: |
            python cli.py --validate \
              << pipeline.parameters.build-link-a >> \
              << pipeline.parameters.build-link-b >>
  info:
    parameters:
      n:
        type: integer
        default: 2
    parallelism: << parameters.n >>
    resource_class: small
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Parse build information
          command: |
            python cli.py --index=$CIRCLE_NODE_INDEX --info \
              << pipeline.parameters.build-link-a >> \
              << pipeline.parameters.build-link-b >>

workflows:
  diff-builds:
    when:
      and: # All must be true to trigger
        - << pipeline.parameters.build-link-a >>
        - << pipeline.parameters.build-link-b >>
    jobs:
      - validate
      - info
