version: 2.1

orbs:
  python: circleci/python@2.0.1

commands:
  python-deps:
    steps:
      - python/install-packages:
          pkg-manager: poetry

parameters:
  build-link-a:
    type: string
    description: build link URL for build A (job)
    default: ""
  build-link-b:
    type: string
    description: build link URL for build B (job)
    default: ""

jobs:
  validate:
    resource_class: small
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python-deps
      - run:
          name: Confirm builds are from the same project
          command: |
            poetry run python cli.py --validate \
              << pipeline.parameters.build-link-a >> \
              << pipeline.parameters.build-link-b >>
  info:
    parameters:
      n:
        type: integer
        default: 2
    parallelism: << parameters.n >>
    resource_class: medium
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python-deps
      - run:
          name: Parse build information
          command: |
            poetry run python cli.py --index=$CIRCLE_NODE_INDEX --info \
              << pipeline.parameters.build-link-a >> \
              << pipeline.parameters.build-link-b >>
      - persist_to_workspace:
          root: .
          paths:
            - job_info
      - store_artifacts:
          path: job_info

  visualize:
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Diff
          command: |
            # diff-so-fancy script v1.4.2
            # See https://github.com/so-fancy/diff-so-fancy
            diff -u job_info/0.yml job_info/1.yml | ./diff-so-fancy

workflows:
  diff-builds:
    when:
      and: # All must be true to trigger
        - << pipeline.parameters.build-link-a >>
        - << pipeline.parameters.build-link-b >>
    jobs:
      - validate
      - info:
          requires:
            - validate
      - visualize:
          requires:
            - info
